export const experienceItems = [
  {
    title: "CyTech International",
    subtitle: "visual designer | visual design team interim manager",
    type: "work",
    period: "2024 - 2026",
    media: "dashboard",
    imageSrc: "/Main%20Dashboard%20-%20Dark.png",
    contributions: [
      "contributed to the development of AQUILA, CyTech's cybersecurity platform, through ui/ux design, product research, qa, and writing user stories and acceptance criteria.",
      "led the creation of a design system for the visual design team, improving workflow speed, consistency, and collaboration.",
      "served as the visual design team interim manager, onboarding new team members and supporting sprint planning and ticket creation.",
    ],
    tags: [
      "Enterprise SaaS",
      "Cybersecurity UX",
      "UX Research",
      "Information Architecture",
      "Design Systems",
      "Cross-functional Collaboration",
      "Requirements Definition",
      "AI-assisted Workflow",
    ],
  },
  {
    title: "ETCMF",
    subtitle: "ui/ux designer | researcher",
    type: "project",
    period: "2023 - 2024",
    media: "devices",
    contributions: [
      "worked closely with the Manolo Fortich Road and Traffic Administration to gather user requirements through surveys and stakeholder interviews.",
      "designed the web and mobile interfaces by translating research findings into simple and user-friendly experiences.",
      "collaborated with the project team to validate requirements and refine the solution throughout the development process.",
    ],
    tags: [
      "User Research",
      "Stakeholder Interviews",
      "UI Design",
      "Mobile & Web",
      "Information Architecture",
      "Usability",
    ],
  },
  {
    title: "Creative Media Roles",
    subtitle: "photographer | videographer | video editor",
    type: "passion & work",
    period: "2018 - present",
    media: "collage",
    contributions: [
      "worked directly with clients to understand project requirements, manage expectations, and deliver creative solutions that met their goals.",
      "produced photo and video content for events, organizations, and commercial projects while balancing quality, timelines, and client feedback.",
      "coordinated with clients and creative teams to plan shoots, manage schedules, and ensure smooth project execution from planning to final delivery.",
    ],
    tags: [
      "Client Communication",
      "Project Management",
      "Creative Direction",
      "Photography",
      "Videography",
      "Video Editing",
    ],
  },
];
